name: flutter_autoupdate
description: Easily add auto update functionality to your Flutter application
version: 1.0.0
author: Victor See<hello@imvictor.me>
homepage: https://github.com/feedmepos/flutter_autoupdate

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  app_installer: ^1.0.0
  crypto: ^3.0.1
  dio: ^5.1.1
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  url_launcher: ^6.0.9
  version: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
